### ISSUE TITLE
Supporting repositories where the zsh file is not at the root directory

### ISSUE THREAD

**Issue by paulhybryant** [zdharma/zplugin#13]
e.g. some modules in prezto https://github.com/sorin-ionescu/prezto
or oh-my-zsh

Another example would be the key bindings for fzf
https://github.com/junegunn/fzf/tree/master/shell

We can use snippets for some of these but we cannot detect changes in those repositories and update the snippets.

**Comment by paulhybryant** [comment]
Any comments?

**Comment by psprint** [comment]
I've finally got back to the project. Snippets are expected ways to manage this:

```zsh
zplugin snippet 'http://github.com/robbyrussell/oh-my-zsh/raw/master/lib/git.zsh'
zplugin snippet 'https://github.com/robbyrussell/oh-my-zsh/raw/master/plugins/git/git.plugin.zsh'
zplugin cdclear -q # <- forget completions provided up to this moment
setopt promptsubst
# Load theme
zplugin snippet 'https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/dstufft.zsh-theme'
```

Update-all updates them now. I know this may not look comprehensive (supports single-file plugins, like the git plugin above), but there is a huge gain in this: no Oh-My-Zsh specific code. I gained `100` `ms` in loading time one month ago thanks to the fact that code isn't cluttered. That said, you describe something that is general – plugin in subdirectory. I will think about this, maybe you have propositions?

Today's changes: https://github.com/zdharma/zplugin#news

**Comment by psprint** [comment]
Snippets can now clone subdirectories via Subversion protocol. It's a swiss-knife solution and Prezto is explicitly supported (with dependencies of the modules). Also, there's a shorthand "PZT::" for the URLs:

```SystemVerilog
% zstyle ':prezto:module:prompt' theme smiley
% zplg ice svn; zplg snippet PZT::modules/prompt
```

**Comment by rage28** [comment]
With the snippets feature how would I load the fzf completions and key-bindings? 

```bash
zplugin snippet "https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.zsh"
zplugin snippet "https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.zsh"
```

I've added the above but it still does not load these snippets

**Comment by psprint** [comment]
I've tried loading first snippet. It seems that it sources, because `echo ${functions[_fzf<TAB` gives this result:
![fzf1](https://user-images.githubusercontent.com/6049288/34379433-90eb66ca-eafb-11e7-9533-de43ce9d58ee.png)

I've also executed `zplugin times` command, and the snippet is reported:
![fzf2](https://user-images.githubusercontent.com/6049288/34379464-a8c93da8-eafb-11e7-8f08-ba4310da7905.png)


This is a common way to handle `fzf` – load plugin as `junegunn/fzf` from Github-releases (`from"gh-r"`) and then source the completion and keybindings script as snippet, because binary release doesn't have them.

Could you try repeating the steps with `$functions` and `zplugin times`?

**Comment by rage28** [comment]
Sorry, my bad... It was sourcing correctly. I thought it wasn't sourcing because the default keybind for fzf history search is Ctrl+R and when I pressed it after zplugin loaded it was still showing the default history search. I just found that I have unbound this key combination by mistake at a later point in my zshrc. You can go ahead and close this issue.

Thanks for your quick response!

**Comment by psprint** [comment]
Ok, n/p
