### ISSUE TITLE
zplugin snippet theme doesn't work

### ISSUE THREAD

**Issue by ncihnegn** [zdharma/zplugin#136]
**Describe the bug**
The prompt is 
```~```
 in which the leading arrow in prompt is missing.
**To Reproduce**
```zplugin snippet OMZ::themes/robbyrussell.zsh-theme```

**Expected behavior**
The prompt should be 
```➜  ~```

**Screenshots**

**Versions:**
 - $ZSH_VERSION == 5.7.1 (x86_64-apple-darwin16)
 - Operating system name and version (uname -a): Darwin Kernel Version 18.6.0

**Additional context**

**Comment by lainiwa** [comment]
Seems like the `local` keyword on the very [first line](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/robbyrussell.zsh-theme#L1) breaks the stuff...

**Comment by ncihnegn** [comment]
You are right. So who is at fault here?

**Comment by lainiwa** [comment]
... the other possible "fix" of the theme would be to change quotes in `PROMPT=` from `'` to `"`.

So the reason it fails is the following:
* The theme weirdly expects the `local` variable to be visible at the same scope as the $PROMPT variable, so that zsh's `setopt PROMPT_SUBST` would substitute the variable inside the `$PROMPT`.
* However, zplugin's snippet must be somewhat more "nested" compared to plain `source` command, and the `local` variable is out of the scope at the moment of substitution.
* If we change the quotes to double, we would thus concatenate the content of the `ret_status` string to the beginning of the `$PROMPT` string. So that substituting this PROMPT would not require zsh to know anything about the `ret_status` variable.

Therefore, I think that the theme's authors should better have chosen either
* not marking the variable as local
* or textual substitution inside the config (using the double quotes)

(like it is in the other themes).

**Comment by ncihnegn** [comment]
Thanks a lot. So this should be for oh-my-zsh.

**Comment by psprint** [comment]
Yeah, it's an Oh-My-Zsh thing, thanks @lainiwa & @ncihnegn !
