### ISSUE TITLE
[New User] What does ‘ice’ mean?

### ISSUE THREAD

**Issue by david-moven** [zdharma/zplugin#150]
edit: for other new users, refer to this link: https://github.com/zdharma/zplugin/blob/master/doc/INTRODUCTION.adoc#some-ice-modifiers

**Is your feature request related to a problem? Please describe.**
It was very confusing first getting started. I noticed it is generally used for applying a modifier to the next zplugin command. is that correct?

**Describe the solution you'd like**
Define ice - in wiki, readme, etc.

**Comment by DundarGoc** [comment]
Yes. An Ice modifier is basically a temporary configuration that only applies to the next zplugin command. After the command all configurations are back to default. It's called Ice because ice melts and is temporary. It's a stretch, I know :).

Ice is briefly mentioned in the Introduction but it's very subpar and hand-wavy at this point. The information is too spread out as well. I'm currently trying to fix it but it may take a while.

**Comment by david-moven** [comment]
Thanks! I thought it was similar to `brew` terminology where you could ‘pour’ a drink (command), or pour it over ice, ice being the modifier.

**Comment by psprint** [comment]
I've added some explanation of the `ice` mods to the [Ice Modifiers](https://github.com/zdharma/zplugin#ice-modifiers) section.

**Comment by david-moven** [comment]
Great, it makes sense! Thanks
