### ISSUE TITLE
multi prompt: Using different p10k  prompts depending on conditions.

### ISSUE THREAD

**Issue by rickysaurav** [zdharma/zplugin#222]
I would like to be able to switch between different prompt configurations for the same prompt. 
For example: switching between p10k-pure and p10k-lean depending on the value of a variable or current directory. 
How would we integrate the above setup with zplugin?

**Comment by romkatv** [comment]
Not really an answer to your question but perhaps `POWERLEVEL9K_<segment>_DISABLED_DIR_PATTERN` is what you are after?

```zsh
# Don't show pyenv prompt segment when in ~/foo.
POWERLEVEL9K_PYENV_DISABLED_DIR_PATTERN='~/foo(|/*)'
```

If this is not sufficient, perhaps you could explain what you are trying to achieve?

**Comment by psprint** [comment]
1. Generate your configs with `p10k configure`, copying `~/.p10k.zsh`to some other file like `~/.p10k_other.zsh`.
2.  I suggest updating powerlevel10k before generating the configs, as recently there was a code for hot reloading of the configs added.
3. Then, set-up Turbo's `unload`/`load` ices to load the configs when `$PWD` changes:

    ```zsh
    # Load within zshrc – for the instant prompt
    zplugin atload'!source ~/.p10k.zsh' lucid nocd
    zplugin load romkatv/powerlevel10k

    zplugin id-as'zplugin-prompt' nocd lucid \
        unload'[[ $PWD != */zplugin.git(|/*) ]]' \
        load'![[ $PWD = */zplugin.git(|/*) ]]' \ 
        atload'!source ~/.p10k_zplugin.zsh; _p9k_precmd' for \
            zdharma/null

    zplugin id-as'normal-prompt' nocd lucid \
        unload'[[ $PWD = */zplugin.git(|/*) ]]' \
        load'![[ $PWD != */zplugin.git(|/*) ]]' \
        atload'!source ~/.p10k.zsh; _p9k_precmd' for \
            zdharma/null
    ```

4. The [effect](https://asciinema.org/a/4wHRagGxRF35jgkJyX4tGtBnj)
 
4. There's one issue – sometimes the prompt doesn't switch instantly, as visible on the recording. I don't know why, as the same solution but switching different prompts [always works](https://asciinema.org/a/WWCrrfpdzijqG0BNHCHQgkbzj).

Thanks for the idea! I was wanting such setup, to denote that I'm working on a project by a different prompt, however completely different one was too much.

**Comment by romkatv** [comment]
> 3. Then, set-up Turbo's `unload`/`load` ices to load the configs when `$PWD` changes:

@psprint  Are there advantages to this code compared to the following simpler alternative?

```zsh
function switch-p10k-config() {
  emulate -L zsh
  case $PWD in
    */zplugin.git(|/*)) local cfg=~/.p10k_zplugin.zsh;;
    *)                  local cfg=~/.p10k.zsh;;
  esac
  [[ $cfg == $current_p10k_config ]] || source $cfg
  typeset -g current_p10k_config=$cfg
}

switch-p10k-config
chpwd_functions+=(switch-p10k-config)
zplugin ice depth=1; zplugin light romkatv/powerlevel10k
```

@rickysaurav If you could explain what you are trying to achieve, I'll be able to suggest a better solution. It's highly unlikely that the solution listed above is the best.

**Comment by psprint** [comment]
There are no real advantages, except maybe when there's no initial sourcing of the initial `~/p10k.zsh` – it'll then detect the newly created parameters in the configuration sourced, and unset them when unloading with `unload''`. So this would ensure that there're no leftovers from the previous configs, however I diffed 2 different configurations and I see that they're pretty 1-to1, so that's rather unimportant.

It had one advantage over Zplugin – it was changing the prompt instantly after the directory switch, however I've just added the scheduler to the `chpwd` hooks, so it's now the same in this regard. One theoretical advantage of the Zplugin setup is the ability to check for other things in the `load`/`unload` conditions.

**Comment by rickysaurav** [comment]
@romkatv  I am looking for a solution where I can change my prompt depending on different types of condition . The conditions may depend on the value of some variable or the current working directory, pretty similar to what @psprint  showed in the recordings. 
The use case that I have in my mind is loading different prompts in different projects and selecting different prompts on different machines like simple prompts on my old laptop and fancier prompts on more powerful machines.

**Comment by romkatv** [comment]
> The use case that I have in my mind is loading different prompts in different projects and selecting different prompts on different machines like simple prompts on my old laptop and fancier prompts on more powerful machines.

This seems like a different use case as it doesn't require hot reloading configurations. You can load one config or the other in `~/.zshrc` depending on the condition. Here's what I do in [my own zshrc](https://github.com/romkatv/dotfiles-public/blob/master/.zshrc):

```zsh
if zmodload zsh/terminfo && (( terminfo[colors] >= 256 )); then
  source ~/.p10k.zsh
else
  source ~/.p10k-portable.zsh
fi
```

`~/.p10k.zsh` is my regular config while `~/.p10k-portable.zsh` is restricted to ASCII and 8 colors. I use it in dump terminals.

>  I am looking for a solution where I can change my p10k prompt depending on different types of condition.

If you could describe the conditions and how you want prompt to look like, I'll be able to suggest a good solution (better than reloading the whole config). Please treat it as an offer rather than a demand.

**Comment by rickysaurav** [comment]
@romkatv  First condition is mostly different prompts for different projects, so that'll essentially be changing prompts depending on the project I am working on. (this might involve hot reloading.)
Second condition usually involves different prompts for different machines , for example: very simple prompts on my older laptop,remote machines, tmux-sessions (since I already have tmuxline) and fancier prompt on my Macbook.
The third would simply involve loading the fancier prompt on my other machines on a whim without reloading the shell, which would not be very often. 
I was intrigued by the fact that zplugin supported hot reloading of prompts based on condition when the prompts were different zsh plugin, and wanted to be able to do the same for the different p10k configurations that I have.

**Comment by romkatv** [comment]
> First condition is mostly different prompts for different projects

Could you clarify what will be different between prompts for different projects? A specific example would be most helpful.

I suppose all style options will be the same? If you find prompt style that works for you, you'll likely want to use it everywhere.

> Second condition usually involves different prompts for different machines

As I mentioned above, this can be achieved with a plain `if` in `~/.zshrc`.

```zsh
case ${(%):-%m} in
  macbook-pro-2015) source ~/.p10k-full.zsh;;
  raspberry-pi-2) source ~/.p10k-light.zsh;;
  ...
esac
```

> The third would simply involve loading the fancier prompt on my other machines on a whim without reloading the shell, which would not be very often.

This is fairly straightforward. You can execute the following command in interactive zsh:

```zsh
source ~/.p10k-fancy-config.zsh
```

> wanted to be able to do the same for the different p10k configurations that I have

You certainly can hot-reload p10k configurations because p10k has explicit support for it. I haven't yet seen a use-case where it would be useful to hot-reload a config based on current directory or some other condition, but perhaps you have one. I'm looking forward to a few more details about "first condition" above.

**Comment by psprint** [comment]
I can just drop-add, that using Zplugin to load the config has an advantage of a more declarative-like approach because it'll use the Zplugin syntax everywhere, i.e.:

```zsh
# Load within zshrc – for the instant prompt
zplugin load romkatv/powerlevel10k

zplugin id-as'zplugin-prompt' nocd lucid \
    load'![[ ${(%):-%m} = macbook-pro-2015 ]]' \ 
    atload'!source ~/.p10k_base_macbook.zsh; _p9k_precmd' for \
        zdharma/null

zplugin id-as'normal-prompt' nocd lucid \
    load'![[ ${(%):-%m} = raspberry-pi-2 ]]' \
    atload'!source ~/.p10k_base_rp.zsh; _p9k_precmd' for \
        zdharma/null
```

Note that there're no `unload''` ices because the configuration is stable, i.e.: not going to be hot-reloaded. However, as the author wants to change the prompts also on directory change, possibly only on one machine, then the instructions will look like:

```zsh
# Load within zshrc – for the instant prompt
zplugin load romkatv/powerlevel10k

zplugin id-as'zplugin-prompt' nocd lucid \
    load'![[ ${(%):-%m} = macbook-pro-2015 && $PWD != */project1(|/*) ]]' \
    unload'![[ ${(%):-%m} = macbook-pro-2015 && $PWD = */project1(|/*) ]]' \
    atload'!source ~/.p10k_base_macbook.zsh; _p9k_precmd' for \
        zdharma/null

zplugin id-as'zplugin-prompt' nocd lucid \
    load'![[ ${(%):-%m} = macbook-pro-2015 && $PWD = */project1(|/*) ]]' \
    unload'![[ ${(%):-%m} = macbook-pro-2015 && $PWD != */project1(|/*) ]]' \
    atload'!source ~/.p10k_project1_macbook.zsh; _p9k_precmd' for \
        zdharma/null

zplugin id-as'normal-prompt' nocd lucid \
    load'![[ ${(%):-%m} = raspberry-pi-2 ]]' \
    atload'!source ~/.p10k_base_rp.zsh; _p9k_precmd' for \
        zdharma/null
```

I think that such an approach has the advantage of single DL (domain-language) -like syntax to cover the topic of selecting the prompt based on different conditions.

**Comment by rickysaurav** [comment]
@romkatv I can totally understand it's not a very practical or common use case, just a whim I had. I prefer really minimal prompts when doing regular stuff on shell but prefer slightly colorful or eye-catching colors when working on a specific project so that the current virtualenv/branch is more differentiable to the eye.
This is my regular prompt: 
![rsz_12019-12-06-22-07-34_2560x1440](https://user-images.githubusercontent.com/13986039/70339645-381ebc00-1875-11ea-8a06-51eecc7f0f4a.png)
This is my prompt when working on a project
![2019-12-06-20-54-19_2560x1440_cropped](https://user-images.githubusercontent.com/13986039/70339118-428c8600-1874-11ea-9500-61fb64ad4f38.png)
@psprint  I tested out your suggested config. It works pretty great for my use case. 
Thanks to the both of you for your great work.I cannot overstate how great it feels to have a crazy fast shell and prompt.

**Comment by romkatv** [comment]
> @psprint I tested out your suggested config. It works pretty great for my use case.
> Thanks to the both of you for your great work.I cannot overstate how great it feels to have a crazy fast shell and prompt.

If you use that code, keep in mind that your prompt may malfunction at any time and/or completely break when you update powerlevel10k. The use case of hot-reloading configs is explicitly supported by p10k but not through the code posted by @psprint.
