### ISSUE TITLE
various feedback

### ISSUE THREAD

**Issue by untoreh** [zdharma/zplugin#30]
unordered collection of minor things:
1. when fetching a snippet but it only is a completions script (like from OMZ) it warns no snippets loaded, something I imagined worked but didn't where `pick""` or `silent`, what worked was creating an empty script and picking that
2. snippets are not automatically compiled on pull, understandably not all snippets are scripts, so either check if it is a script on pull/clone or provide an ice mod to request compilation?
3. `compile --all` doesn't compile zpl or snippets, zpl is not compiled until you run the first `self-update` which is not something you do when you first install zpl
4. `as"command"` clutters the `$PATH`. Linking all the bins to a single path would be better, not only to avoid unnecessary lookups but to provide a path also for non interactive scripts which do not load all the zpl config but might need some bins
5. `pick` works only with one script, since `bpick` was added for binaries I imagine like `mpick` when you want multiple scripts? for example from `OMZ::lib/` I just used a for loop on `atinit` to source what I needed. There is also another cool trick, that is, you can pass something like `"OMZ:lib/{misc.zsh,spectrum.zsh,termsupport.zsh}"` and I have not checked but I guess it is `curl` that parses this syntax and downloads all the scripts and concatenates them, although if the scripts use overlapping variables I imagine it is not very safe to do.
6. would you consider it a sane default if `zpl times` was just `zpl times | sort`? I imagine that is what most people would expect
7. `zpl create` does not follow ice mods, so you can't issue something like setup commands in case a plugin folder doesn't exist
8. being able to specify `ice`defaults would be nice, use case like `depth"1"` for a bunch of repos
9. `gh-r` didn't handle `gz` non tarred files, had to do a `atclone'gunzip file*; mv file* file; chmod+x file '`

**Comment by psprint** [comment]
> 1. when fetching a snippet but it only is a completions script (like from OMZ) it warns no snippets loaded, something I imagined worked but didn't where pick"" or silent, what worked was creating an empty script and picking that

I did something towards `_completion` fetching with single-file snippet (is this what you do? URL points to _file and there is no svn ice?) but didn't finalize. It would be nice to support this fully, after feedback I will implement this.

> 2. snippets are not automatically compiled on pull, understandably not all snippets are scripts, so either check if it is a script on pull/clone or provide an ice mod to request compilation?

Single-file snippets are compiled on install and update. I didn't yet implement this for multi-file svn snippets because as you noticed not every file is a script, however I now see, that I could do at least "if-not-as-command then compile", because if someone wants to source a file, it is a script. I will implement this, maybe also with request-compilation ice.

> 3. compile --all doesn't compile zpl or snippets, zpl is not compiled until you run the first self-update which is not something you do when you first install zpl

Thanks for pointing this out.

It is hard to compile zplugin in installer because user might use different Zsh than `/usr/bin/zsh`, e.g. `/usr/bin/zsh-5.4.2`, and compiled `zwc` files are version-dependent. I might however add a message to the installer "Compile zplugin with zplugin self-update".

> 4. as"command" clutters the $PATH. Linking all the bins to a single path would be better, not only to avoid unnecessary lookups but to provide a path also for non interactive scripts which do not load all the zpl config but might need some bins

This would be on TODO list, doable in 5 months.

> 5. pick works only with one script, since bpick was added for binaries I imagine like mpick when you want multiple scripts? for example from OMZ::lib/ I just used a for loop on atinit to source what I needed.

I minimize the code, want things in few lines, I was thinking on multi-pick but it would add a block of code. I've chosen to wait and see what will come up in issues, e.g. your tricks can be helpful in this. Also, there's `src` ice, so +1 file can be sourced. For `as"command"`, when `pick` matches multiple files, then:
- surrounding directory of first one is added to `PATH`,
- first file is checked for +x access right, if no such right, then **all matching files** are given +x.

So this quite solves the problem of adding a plugin/snippet with multiple commands. I check only 1 file for +x to speed up loading.

> There is also another cool trick, that is, you can pass something like "OMZ:lib/{misc.zsh,spectrum.zsh,termsupport.zsh}" and I have not checked but I guess it is curl that parses this syntax and downloads all the scripts and concatenates them, although if the scripts use overlapping variables I imagine it is not very safe to do.

Tested this, had to quote the expression, but it works, downloads 1 file that is concatenated. Interesting, thanks. I checked that wget also works, and it's probably because of common URL standard: https://curl.haxx.se/docs/manpage.html#URL

Little weird that it was slow once, then fast, using curl.

> 6. would you consider it a sane default if zpl times was just zpl times | sort? I imagine that is what most people would expect

I expected the "| sort" trick to happen constantly. The order of loading is an information that is gathered, I thought it's useful to present this information, allowing user to sort if needed. The only solution is option for loading-order sorting and default time-order sorting, I will think on this.

> 7. zpl create does not follow ice mods, so you can't issue something like setup commands in case a plugin folder doesn't exist

Could you show an example of such setup commands?

> 8. being able to specify icedefaults would be nice, use case like depth"1" for a bunch of repos

Yes that's rather expected, it's just that it makes commands more complex, and I would have to update zplugin-crasis.

> gh-r didn't handle gz non tarred files, had to do a atclone'gunzip file*; mv file* file; chmod+x file '

Thanks, I'll fix this.

**Comment by untoreh** [comment]
> (is this what you do? URL points to _file and there is no svn ice?) 
svn is specified, by pointing to the `_file` directly it sources it which is not what you want, it does not warn if as"command" is specified, but then it adds an extra entry to the PATH for nothing

> Could you show an example of such setup commands?
like distro specific package management, or services/systemd stuff or you just want to cache something? Like you could keep a repo int `/tmp` and just create it once on every startup? I don't know maybe I am going too far with this.

**Comment by untoreh** [comment]
I think I have isolated a weird behaviour, testing on a clean zshrc with just the three lines from zpl:
- start a shell
- press `ALT+x`
- the `execute` prompt shows up, wait 2-3 seconds
- press `CTRL+c` to close and notice it is unresponsive

Without zpl the first `CTRL+c` should close the execute prompt and the second spawn a new line.

**Comment by psprint** [comment]
TODO:
- [ ] support completion-only SVN snippet
- [ ] compile SVN snippets that are not `as"command"`
- [ ] decide whether to add request-compilation ice, implement
- [ ] update `compile --all` and `compile` to support snippets
- [ ] decide if `src` should obtain multiple file names and/or patterns, implement
- [ ] expose Curl (not wget, double-checked) complex-URL feature `../{file1,file2}`
- [ ] develop `repo created once every startup` idea
- [ ] add non-tar `*.gz` etc. support to `from"gh-r"`

**Comment by psprint** [comment]
Hello,
just letting know that the proposed request-compilation ice has been implemented ([details](https://github.com/zdharma/zplugin#news)).

**Comment by untoreh** [comment]
nice, I am gonna have to check how to integrate it with the functions which I was currently using which are these, also the zcompdump stuff
```shell
function zpld (){
    [[ -a ~/.zplugin/.zdown ]] && return 1

    ## home files
    touch ~/.zplugin/black_list
    zlist=$( find ~/.zplugin/* -type f \
                  -size +1 -a -size -1048576c \
                 -regextype posix-egrep \
                 -regex ".*\..*sh$|.*\/\.?[^.]*$" \
                 -a -not -regex ".*\/\.zplugin\/.*\/\..*\/.*" | \
         grep -Fvf ~/.zplugin/black_list)
    hlist="$(find ~/{.zshrc,.zprofile,.profile,.zshenv,.zlogin,.zlogout,.zcompdump,.zcompcache/*} 2>/dev/null)"
    file_list=$zlist'\n'$hlist

    IFS=$'\n'
    for i in $(echo "$file_list"); do
        zcompile $i &>/dev/null || echo $i >> ~/.zplugin/black_list
    done

    sys_list="$(sudo find /etc/zsh/{zshrc,zprofile,zlogin,zlogout,zshenv})"
    for i in $(echo "$sys_list"); do
        sudo zsh -c "zcompile $i"
    done

    touch -f ~/.zplugin/.zdown
    unset FPATH
    exec zsh -li
}
function zplu (){
    IFS=$'\n'
    for i in $( find ~/.zplugin -type f -name \.zwc ) ; do
        rm -f $i
    done
    for i in $( find {~/\.*,~/.zcompcache/*} -maxdepth 0 -type f -name "*\.zwc" ) ; do
        rm -f $i
    done

    sudo rm -f /etc/zsh/*.zwc

    rm -f ~/.zplugin/.zdown
    if [[ "$1" == "re" ]] ; then
        exec zpld
    else
        exec zsh -li
    fi
}
function zplr(){
    zplu re
}
```
