### ISSUE TITLE
How to load commands like Enhancd and Sentaku

### ISSUE THREAD

**Issue by The-BigDaddy** [zdharma/zplugin#48]
I've been trying to get [Enhancd](https://github.com/b4b4r07/enhancd) and [Sentaku](https://github.com/rcmdnk/sentaku) to work with Zplugin, however I've been unsuccessful. I'm not entirely sure what exactly to `pick""` and `src""` for those plugins given their directory structures. Here's what I have right now in my `~/.zshrc`
   
```
    # enhancd
    zplugin ice from"gh" as"program" wait'2' pick"init.zsh" lucid 
    zplugin load b4b4r07/enhancd

    # sentaku
    zplugin ice from"gh" as"command" wait'2' pick"bin" lucid 
    zplugin load rcmdnk/sentaku
```

Again, this doesn't work but I'm not entirely should what I should change. I've tried a lot of different things but I've yet to have any success.

**Comment by psprint** [comment]
Enhancd is a regular plugin. It works after `zplugin light b4b4r07/enhancd`. It might be unclear if the plugin is loaded, because it activates when `cd` is entered, and I think not always, but plugin report clarifies, that it does `alias cd=...`:

```
Plugin report for b4b4r07/enhancd
---------------------------------
Source init.sh (reporting enabled)
Alias cd=__enhancd::cd

Functions created:
__enhancd::arguments::dot             __enhancd::arguments::empty
...
```

Your command for sentaku is almost correct, but it should say `pick"bin/sentaku"`, it then works (tested with `echo a b c | sentaku`).

**Comment by yangxyo** [comment]
```
zinit wait"1" lucid light-mode for 
    \b4b4r07/enhancd
```
the terminal show:
`compinit:503: no such file or directory:  ~/.zinit/completions/_enhancd_`
I checked it:
1. The symbol links broken.
2. The real resources are in `b4b4r07---enhancd/conf.d` rather than `b4b4r07---enhancd/src` like other plugins.
