### ISSUE TITLE
Infinite loop with decimals in `zplugin ice wait"0.2"`

### ISSUE THREAD

**Issue by HaleTom** [zdharma/zplugin#57]
If I have:

```
zplugin ice wait"0.2"
zplugin light zdharma/fast-syntax-highlighting
```

I see a repeating:
```
(eval):1: command not found: 0.2
```

**Comment by robobenklein** [comment]
I think this is because seconds are being used as the base math unit. (Integer form.)

In code I see that `$EPOCHSECONDS` is being used with addition to the wait.

In `-zplg-scheduler` the resolution of intervals is only 1 second, being performed with the `sched` zsh utility, which doesn't support sub-second resolution anyways.

http://zsh.sourceforge.net/Doc/Release/Zsh-Modules.html#The-zsh_002fsched-Module

**Comment by psprint** [comment]
I've added fractional waiting time handling to not loop with constant error message. The time resolution is 1 second, that's true, fractional part of number will be discarded, but there's one trick in the sleeve (`zle -F` handler), however there are problems that might not be solvable (currently working on this).

**Comment by psprint** [comment]
@ericfreese: Could you maybe help? I have major problems with `zle -F` handlers, I've tried:

```zsh
        zpty -b fast-zero LANG=C sleep 0.2\; echo run
        zle -N zplg-scheduler -zplg-scheduler
        zle -F -w "$REPLY" zplg-scheduler
```

and 

```zsh
        exec {MYFD}< <(LANG=C sleep 0.2; echo run;)
        zle -N zplg-scheduler -zplg-scheduler
        zle -F -w "$MYFD" zplg-scheduler
```

This runs code after Zsh startup. I then enter "abc" and press Ctrl-C – and sadly I need to press it twice to get effect of aborting a command. Then I can enter 1, maybe 2 characters and command line is in freeze, only Ctrl-C provokes some reaction.

Removing the 3 lines makes all problems go away. I wonder how you managed to add async support for zsh-autosuggestions because I get also user reports for fast-syntax-highlighting (async path checking via <()) and with the above I must conclude that `zle -F` is unusable :( Have you maybe occurred those problems but solved it?
