### ISSUE TITLE
Ability to manage `bindkey`s

### ISSUE THREAD

**Issue by HaleTom** [zdharma/zplugin#69]
**Is your feature request related to a problem? Please describe.**

I load everything I can using `wait` for fast startup.

The issue is the `bindkey` for `^R`. 

`softmoth/zsh-vim-mode` binds `^R` to `history-incremental-pattern-search-backward`.

But actually, I want the [binding provided by `fzf`](https://github.com/junegunn/fzf#key-bindings-for-command-line), which lets me select a history item from a list.

The issue is that for `fzf` I need to:
```
source    /usr/share/fzf/key-bindings.zsh
source    /usr/share/fzf/completion.zsh
```
This is executed sequentially, before the `wait` load of `softmoth/zsh-vim-mode`. So `fzf`'s `bindkey`s are overwritten by `softmoth/zsh-vim-mode`'s turbo load.

**Describe the solution you'd like**
Could `zplugin` manage `bindkey`s for each plugin like it does with completions?
Could certain `bindkey`s be suppressed?

**Describe alternatives you've considered**
Allowing arbitrary code execution in `wait` is a workaround solution. This would allow the `source`ing of the `fzf` files after `softmoth/zsh-vim-mode` loads. (See https://github.com/zdharma/zplugin/issues/68)

This would solve my issue in this case, but would still not allow specific `bindkeys` to be suppressed to hand pick which ones end up being active.

**Comment by robobenklein** [comment]
I think this is a good feature request! Bindkeys are already tracked, so it seems there could be a capture/replay for them as well similar to `zcdreplay`.

Then in addition, we have `clist`, could we also get a `blist`? (bindkey list)

**Comment by psprint** [comment]
This is interesting, first thing that I thought is that having ability to overview defined bindkeys would be good. So I pushed a new `bindkeys` subcommand, that lists them:

![zplg-bindkeys](https://user-images.githubusercontent.com/6049288/43999290-ecf4c8dc-9e09-11e8-9621-d57404a9f2aa.png)

I guess they should be listed in order of loading, but user can look at `zplg times` for now. Requires to load the plugin with `load` not `light`, but with turbo-mode one can afford this. I could add limited tracking mode, `light -b`, that would track only bindkeys.

I thought that bindkey is an important Zsh feature that is currently hold back because of possible collisions. So I thought that one of the bindkey-managing functionality could be an ability to override the key sequences inside plugin with:

```zsh
zplugin ice bindkeys'^R ^T ^O^K'
zplugin load some/plugin
```

Zplugin would substitute the key sequence from the `bindkeys` list for key sequences hardcoded in the `bindkey` calls inside plugin, in order.

**Comment by HaleTom** [comment]
With the line:
```
zplugin ice bindkeys'^R ^T ^O^K'
```

Is the intention to *only* allow binding of those particular keys?

I'd suggest that blacklisting would be a more user-friendly way, allowing only the unwanted `bindkey`s to be blocked. 

A classic example of why blacklisting would be preferred is:

```
% grep bindkey zsh-vim-mode.plugin.zsh | wc -l 
55
``` 


Preventing `bindkey`s would only need to be done for the later-loaded plugins to prevent overwriting, which is why I believe blocking `bindkey`s to be a more common use case.

--------

`light -b` sounds like a great idea.

**Comment by psprint** [comment]
No, the line:
```zsh
zplugin ice bindkeys'^R ^T ^O^K'
```
would instruct Zplugin to take first bindkey done in plugin, replace it's target key with Ctrl-R, execute it, then go execute normally until second bindkey occurs, what will be also trapped, the target key in the bindkey replaced with Ctrl-T, execution resumed, till 3rd bindkey, which will have the target key sequence replaced with Ctrl-O Ctrl-K and then executed.

So basically an overlay with key sequences to apply on bindkey commands of plugin. The information about order in which particular bindkeys occur inside plugin can be taken from report.

Yeah I'm pretty close to implement `light -b`.

**Comment by psprint** [comment]
True about the 50th bindkey, this would require a syntax to specify the number of bindkey, i.e. `bindkey'[50] ^T'` but I'm unsure about how quickly this could be parsed and if there's a better syntax.

The blacklist approach, to protect existing bindkeys. It's quite easy to implement. It can be done like you've described, no tracking is required in that case. Or with tracking – detect protected key, skip actual bindkey for it. I would go with your method.

However, don't you think this is somewhat "circling around" plugins, not taking control over bindkeys but choosing the wanted ones from what's already there in the plugins? I think this would not fully solve bindkey collisions and authors of plugins could still choose to leave bindkey stuff for users, like e.g. `zsh-users/zsh-history-substring-search` does (it doesn't provide any bindkeys). I know, Zplugin "doing bindkeys right" will not suffice to encourage authors to provide default bindings, but at least one plugin manager out there would be on the right path.

**Comment by HaleTom** [comment]
Doesn't `bindkey[50]` have the assumption that the order of the existing `bindkey`s will stay the same in updated releases of that plugin?

It sound positive that the blacklist approach is easy to implement. 

Personally, I'm not after a complete `bindkey` management solution. I'm after something that solves the most common case - preventing an unwanted `bindkey`.

----

This may be the common ground, allowing for a more holistic solution:

If there if is a `bindkey` collision, instead of trying to work out what other plugin (or possibly more than one) is doing causing it, there could be a global hold put on binding that key, perhaps something like:
```
zplugin bindhold '^T' '^R' ...
```

If `^T` is actually desired to be bound by a plugin, perhaps:

```
ice bind'^T'
```
Could allow one specific plugin to override the `bindhold` on that key combo.

It would make sense to issue a warning if more than one plugin tried to `ice bindkey` the same key combination.

Cheers for such a great plugin manager!  Your attention to detail is greatly appreciated.

**Comment by psprint** [comment]
I've received a donation (thanks!) and implemented this feature:

![bindmap](https://user-images.githubusercontent.com/6049288/47444549-00f76380-d7b7-11e8-94bc-ca18d11b6c3a.png)

What's left is the `bindkey`-only tracking to be implemented, and the few symbolic names for keys like `UPAR`, `DNAR`, `HOME`, etc. to be set up. Unloading is working, i.e. it deletes the remapped key sequence, not the original one.

**Comment by HaleTom** [comment]
Cheers!  This is looking great!

I've just PayPaled you some... If you get around to the `light -b` or `trackbinds` that you mentioned that would be be appreciated!

**Comment by psprint** [comment]
I've done a part on the `UPAR`, `LEFTAR`, etc. symbolic names for multiple cursor escape sequences per direction. The symbolic names can be used on the left side of a bindmap, to detect a set of sequences that are a cursor, not just one:

![upar](https://user-images.githubusercontent.com/6049288/48436326-b5fdba00-e77e-11e8-8c1f-ca0dc51d2179.png)

**Comment by psprint** [comment]
Guys is there a small motivation possible, like $5? I could implement 2 other abilities: **(A)** `bindmap"^R -> UPARR"`, i.e. UPARR on the right side of `bindmap`.

I know that the `UPAR`, etc. might not actually have an use case, especially on the left side. However I will add HOME, END, PGUP, PGDOWN, etc. too, so this will become rather useful. I'm doing this mostly for how nice it is to solve the termcap&terminal-inconsistencies that very often occur.

**(B)** The second ability would be: new ice-mod `bk` used like e.g.: `bk"[1] <- UPAR"`, which will mean: bind 1st created Zle widget to UPAR (this means like 3-4 `builtin bindkey ...` calls, because, like we already know, UPAR is a set of escape codes that happen to exist for this keyboard key; however, `bindkey` supports unlimited number of arguments, so code will be still nice). This is for plugins like [zsh-history-substring-search](https://github.com/zsh-users/zsh-history-substring-search), which instruct users (in READMEs) to add multiple lines like `bindkey '^[[A' history-substring-search-up` etc. into their zshrc, which for me is little wrong, to apply manual actions in case of an automatic loading of plugins. With this second ability, user would need only to:

```zsh
zplugin ice bk"[1] -> UPAR; [2] -> DOWNAR"
zplugin zsh-users/zsh-history-substring-search
```

And he will obtain a working setup, free from bound zshrc snippets (the bindkey calls). This means easy copying of the .zshrc to other machine, etc.

My paypal-email is `sgniazdowski / gmail.com`, I would then quickly approach those features.

**Comment by dufferzafar** [comment]
Has this feature been removed now? I don't see any mention of bk UPAR / DOWNAR thing on the docs

**Comment by psprint** [comment]
No, it's there, just undocumented

sob., 11 kwi 2020, 23:32 użytkownik Shadab Zafar <notifications@github.com>
napisał:

**Comment by psprint** [comment]
I've added the documentation of the feature: [here](https://zdharma.org/zinit/wiki/Bindkeys/).

**Comment by dufferzafar** [comment]
Thanks! Somewhere I noticed a mention of `id_as` ice - which seems to be missing from the readme as well. Is that also undocumented? or Has it been removed?

**Comment by psprint** [comment]
It's `id-as`. It's documented in the README and on [the Wiki](https://zdharma.org/zinit/wiki/id-as/).

**Comment by HaleTom** [comment]
It's probably worth noting that with `wait`,  `trackbinds` is necessary for `bindmap` to have any effect.

**Comment by psprint** [comment]
I think that's not true, `trackbinds` is needed when `light`/`light-mode` is being used.
