### ISSUE TITLE
How to install agnoster theme?

### ISSUE THREAD

**Issue by alo0oz** [zdharma/zplugin#75]
I have downloaded the agnoster theme from github.but now i'm at a loss how to install it using zplugin.

**Comment by leoj3n** [comment]
You can see the `~/.zshrc` in this sandbox of how the "pure" theme is sourced using Zplugin:

https://glitch.com/edit/#!/remix/zplugin-sandbox

**Comment by leoj3n** [comment]
You will have to make a similar command for `agnoster` but specify whatever files it uses, then run `zplugin compile`. However, I'm new to Zplugin as well so take my intuition with a grain of salt.

Hope this helps.

**Comment by leoj3n** [comment]
One final comment—You let Zplugin download from GitHub for you, after you edit `~/.zshrc` and run `zplugin compie` the Zplugin tool will see that it has not yet downloaded `userX/repoY` and do that for you. If you are needing to customize a fork of agnoster you will have to skim through the Zplugin README to see how to pull in a local repo or whatever.

**Comment by psprint** [comment]
@alo0oz If you downloaded a zip archive, then unpack it into some {agnoster-directory}, and issue:

```zsh
zplugin light /path/to/{agnoster-directory}
```

You can add this line to zshrc. You can also install directly from Github, by issuing:

```zsh
zplugin light agnoster/agnoster-zsh-theme
```

I've tested this (used command `load` instead of `light`, to load with reporting; it's slower), it looks like below:
![agnoster-load2](https://user-images.githubusercontent.com/6049288/44418682-5629b580-a579-11e8-9661-0bcf7fa7ef5f.png)

As you can see there are weird characters in the prompt. That's because this prompt requires **patched fonts**.


As it is interesting to look, I also attach zplugin report for this plugin:

```
myprompt% zplugin report agnoster/agnoster-zsh-theme
Plugin report for agnoster/agnoster-zsh-theme
---------------------------------------------
Source agnoster.zsh-theme (reporting enabled)
Autoload add-zsh-hook with options -U -z
Autoload vcs_info with options -U -z
Autoload prompt_agnoster_precmd
Zstyle :vcs_info:* enable git
Zstyle :vcs_info:* check-for-changes false
Zstyle :vcs_info:git* formats %b
Zstyle :vcs_info:git* actionformats %b (%a)

Functions created:
prompt_agnoster_main  prompt_agnoster_precmd
prompt_agnoster_setup prompt_context
prompt_dir            prompt_end
prompt_git            prompt_segment
prompt_status         prompt_virtualenv
vcs_info

Variables added or redefined:
BRANCH             [ "" -> scalar ]
PLUSMINUS          [ "" -> scalar ]
DETACHED           [ "" -> scalar ]
SEGMENT_SEPARATOR  [ "" -> scalar ]
PRIMARY_FG         [ "" -> scalar ]
CURRENT_BG         [ "" -> scalar ]
LIGHTNING          [ "" -> scalar ]
prompt_opts        [ "" -> array  ]
CROSS              [ "" -> scalar ]
GEAR               [ "" -> scalar ]
```

@leoj3n Interesting sandbox, I have to look closer at this.
