### ISSUE TITLE
Zplugin should hijack add-zsh-hook

### ISSUE THREAD

**Issue by jolan78** [zdharma/zplugin#78]
- Problem:

Unloading plugins do not unhook its functions. ex: unloading agnoster.zsh-theme will produce an error at each prompt because it tries to call an unloaded function

- Solution:

Zplugin could hijack add-zsh-hook in order to unhook on unload

- Alternative solution:

Another less clean solution would be to provide an atunload ice modifier in order to manually unhook

**Comment by psprint** [comment]
Yes this is in general needed. It isn't there yet because current solution, which `unfunction`s all functions including the hook somewhat works – when the function in `precmd_functions` or other hook array doesn't exist, it simply isn't called and no error message appears. Do you see an actual error message?

**Comment by jolan78** [comment]
yes I do.
I get "zsh: command not found: prompt_agnoster_main" before each prompt if i do not unhook manually.
note that I use my own version of agnoster (jolan78/agnoster-zsh-theme) but the hooking mechanism is the same.

**Comment by psprint** [comment]
The idea of "unhook on unfunction" is perfect, sorry that I've didn't react quicker! The patch is very simple – it filters e.g.:

```zsh
        (( ${+precmd_functions} )) && precmd_functions=( ${precmd_functions[@]:#$f} )
        ...
```

`:#` is array filtering, `$f` is the function being currently unset. That's all that's needed, it's pushed to master.
