### ISSUE TITLE
zplg-run-task:4: bad set of key/value pairs for associative array

### ISSUE THREAD

**Issue by HaleTom** [zdharma/zplugin#80]
**Describe the bug**
Every second, I see:
```
zplg-run-task:4: bad set of key/value pairs for associative array
```

**To Reproduce**
In `.zshrc`:
```
declare -A ZPLGM
ZPLGM[HOME_DIR]=$XDG_DATA_HOME/zplugin
source "$XDG_DATA_HOME/zplugin/bin/zplugin.zsh"
autoload -Uz _zplugin
# shellcheck disable=SC2154,2034,2004
(( ${+_comps} )) && _comps[zplugin]=_zplugin
```

**Expected behavior**
No error message.

**Additional**
The line referenced by the error is:
```
    ZPLG_ICE=( "${(@Q)${(z@)ZPLGM[WAIT_ICE_${__idx}]}}" )
```

I think what's happening is that all other entries in $ZPLGM are null if I `declare -A ZPLGM
` :

```
% echo $ZPLGM[PLUGINS_DIR]

%
```

The `readme.md` says to use `local -A ZPLGM`, but this won't work outside a function.

**Versions:**
 - $ZSH_VERSION == zsh 5.5.1 
 - Operating system name and version (uname -a): Linux svelte 4.16.18-1-MANJARO #1 SMP PREEMPT Tue Jun 26 15:27:59 UTC 2018 x86_64 GNU/Linux

**Comment by psprint** [comment]
I've changed `local` to `declare` (coding Zsh I've discovered there's not much or no difference in those keywords). I've created `~/zdotdir/.zshrc` with contents from the issue and ran `ZDOTDIR=~/zdotdir zsh -i` but the problem doesn't reproduce. I've had it when `compinit` was called from `wait'x' atinit'zpcompinit'` plugin and there were insecure directories, but I've assumed the cause was Zsh bug that I've reported. Maybe the problem needs something more to reproduce?
